id: P3A3998BF
initial_creation_type: input
source_metadata:
  title: Dharma Protectors Series
  language: en
  description: 'The following texts are now available as part of our Dharma Protectors
    (dharmapāla; Tib. chos skyong) series:'
  volume:
    bf24394dff3542739e8c67b11060cb64:
      title: Brief Dharmapālas Offering
      parent: General
    75e52bc75b2f4b0e941fdc4aa3889363:
      title: Brief Protectors Practice
      parent: General
    95f5329e464f4eb0a46eab33eddcd0b7:
      title: Expeditious Activity Torma Offering
      parent: General
    1435c98b482c479f9c4af5b903d7bfe8:
      title: Wayfaring Offering
      parent: General
    c14534fec34a4b40b9c2dea3ec02bb27:
      title: A Practice of Fulfilment and Confession to an Ocean of Oath-bound Protectors
      parent: General
    d4db7c77239f4ac5bb84193ed2178969:
      title: 'Damchen Chitor: A Brief Practice of Torma Offering to the Oath-Bound
        Guardians'
      parent: General
    b04a1bb4c1ea41569f0a3dd4e0452c41:
      title: Offering Prayer to Changshönma, Protectress Riding upon a Wolf
      parent: Changshönma
    eb56827c9a2d4c0bb85a8c4aea5fde90:
      title: Brief Offering Prayer to Durtrö Lhamo, Mistress of the Charnel Ground
      parent: Durtrö Lhamo
    227db08c449a4fd3bd080cf7e7cfe9d2:
      title: Golden Drink (Serkyem) and Torma Offering
      parent: Eight Classes
    44e634fef31d41f29cb2fdb7b67eaccc:
      title: Restorative Offering to the Eight Classes
      parent: Eight Classes
    bec879fa92ff4cf09787757a2ca73e6a:
      title: Brief Offering Prayer to Ekajaṭī
      parent: Ekajaṭī
    d657539fa2b143138610ecfd98480f57:
      title: Offering to the Five Medicine Sisters, Guardians of the Earth
      parent: Five Medicine Sisters
    4ba515df1dc1497cbd41443b0c07c421:
      title: Petitionary Offering to Norbu Dradül Tsal
      parent: Gesar
    849a4c527f704bc6905219ab544baf70:
      title: Brief Offering Prayer to Gesar
      parent: Gesar
    f27f7b1f4d3143e097d589b2432bbc34:
      title: 'Sweet Melody to Delight the Glorious Deity: In Praise of Śrī Kālīdevī'
      parent: Kālīdevī
    26e8f80d3a54467991624c579f7e58ea:
      title: 'Swift Enlightened Activity: A Concise Ceremony of Offering and Prayer
        to Mahākāla and Consort'
      parent: Mahākāla
    9b0566cc96ea4261860fa3949201e658:
      title: 'The Fulfilment of All Wishes: Prayer and Entrustment of Activity to
        the Glorious Guru Mahākāla Pañjaranātha'
      parent: Mahākāla
    777083c0744d43c7a904b91c6744b588:
      title: 'Bestower of Supreme Accomplishment: A Torma Offering to Mahākāla'
      parent: Mahākāla
    03ebaae15f574c5a898e28bdcdcbdecc:
      title: 'Pacifying the Turmoil of the Mamos: A Concise Liturgy'
      parent: Pacifying the Turmoil of the Mamos
    655c5b29b97f4fa8b93ce230fefda0ed:
      title: Brief Prayer for Pacifying the Turmoil of the Mamos
      parent: Pacifying the Turmoil of the Mamos
    8f5eb45f2b2746e4b8db7d0f53c582bf:
      title: A Brief Petitionary Offering to the Mātṛkā Pukkasī, Local Protectress
        of the Jarung Kashor Stūpa
      parent: Pukkasī
    a87bf35748c8436fbbac533090af7c03:
      title: Brief Offering Prayer to Za Rāhula
      parent: Rāhula
    3a000924181d4b3abe4e8c5b457e037b:
      title: Serkyem (Golden Libation) Offering to the Guardians of the Tradition
      parent: Serkyem
    98f7a377aa224bad9a055bc1e6384b29:
      title: Brief Offering Prayer to Tsiu Marpo
      parent: Tsiu Marpo
    ac057e767f904e179aeab6fd282b2c10:
      title: Brief Offering Prayer to the Oath-Bound Vajrasādhu
      parent: Vajrasādhu
    188aa8c39208474e99e00a51cba35b23:
      title: Yarlha Shampo Sang Offering
      parent: Yarlha Shampo
created_at: '2022-03-01T03:27:20.279574'
last_modified_at: '2022-03-01T03:27:20.279581'
